version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    ignore:
      - dependency-name: "example-name"
        # For Lodash, ignore all updates
    open-pull-requests-limit: 15
