name: Design Changes Workflow

on:
  workflow_dispatch:
    inputs:
      description:
        description: 'What are we updating (eg. update button destructive color)?'
        default: ''
        required: true
      jira:
        description: 'What is the related Jira (eg. SW-1234)?'
        default: ''
        required: true
      email:
        description: 'Your terraformation email'
        default: ''
        required: true

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  # Cancel in-progress builds on PRs, but not on staging deploys.
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Create branch
        run: git checkout -b $(echo design-workflow-${{ github.actor }}-${{ github.event.inputs.jira }}-$(date +%y-%m-%d-%s) | tr ' ' -)

      - name: Install Dependencies
        run: |
          npm pkg delete dependencies
          yarn install --network-timeout 100000
          git checkout package.json
          git checkout yarn.lock
          git status

      - name: Build dictionary
        run: yarn build-dictionary

      - name: Config user
        run: |
          git config --global user.email ${{ github.event.inputs.email }}
          git config --global user.name ${{ github.actor }}

      - name: Commit changes
        run: |
          git add -A
          git commit -m "$TITLE"
        env:
          TITLE: '${{ github.event.inputs.jira }} ${{ github.event.inputs.description }}'

      - name: Push changes
        run: git push -u origin `git branch --show-current`

      - name: Create PR
        run: gh pr create --fill
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
