name: Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Environment
        run: ./.github/scripts/set-environment.sh
        env:
          NPM_REGISTRY_AUTH_TOKEN: ${{ secrets.FAKE_SECRET }}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: |
          yarn install
          git checkout -- package.json
      - name: linter
        run: yarn lint

      - name: test
        run: yarn test

      - name: build
        run: yarn build-dist

      - name: license report
        run: yarn license-report

      - name: update npm registry
        run: ./.github/scripts/update-npm.sh
        env:
          ARTIFACT_REGISTRY_PROVIDER: ${{ env.ARTIFACT_REGISTRY_PROVIDER }}
          ARTIFACT_REGISTRY: ${{ env.ARTIFACT_REGISTRY }}
          ARTIFACT_REGISTRY_AUTH_TOKEN: ${{ env.ARTIFACT_REGISTRY_AUTH_TOKEN }}
