name: Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Environment
        run: ./.github/scripts/set-environment.sh
        env:
          NPM_REGISTRY_AUTH_TOKEN: ${{ secrets.FAKE_SECRET }}
          TEST_VAR: ${{ secrets.FAKE_SECRET }}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: |
          yarn install
          git checkout -- package.json
      - name: linter
        run: yarn lint

      - name: test
        run: yarn test

      - name: build
        run: yarn build-dist

      - name: license report
        run: yarn license-report

      - name: compare artifact package version
        run: ./.github/scripts/compare-artifact-package-versions.sh
        env:
          ARTIFACT_REGISTRY_PROVIDER: ${{ env.ARTIFACT_REGISTRY_PROVIDER }}

      - name: publish npm package
        if: env.UPDATE_NPM_PACKAGE == 'true'
        run: |
            npm config set @terraware:registry https://registry.npmjs.org
            npm config set https://registry.npmjs.org/:_authToken ${{ secrets.NPM_REGISTRY_AUTH_TOKEN }}
            cd dist && npm publish --scope @terraware
