name: Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: |
          yarn install
          git checkout -- package.json
      - name: linter
        run: yarn lint

      - name: test
        run: yarn test
